### ISSUE TITLE
Books Enchantment Crit Error

### ISSUE THREAD

**Issue by Starmaster** [Mine-and-blade-admin/Battlegear2#194] opened 2015-09-11 14:39 UTC
Hi... i have a server with mods! 1.6.4 all work perfect but when i enchant the weapons any... grabs error, the server kick me for internal error, i can wear, use and play in the server with the MB battlegear2 but i cant use the enchants.

1.6.4-MB_Battlegear2-Bullseye-1.0.5.3.jar      Mar 16, 2014  last of the 1.6.4
cauldron bukkit-1.6.4    version 1.965.21.204 last of the 1.6.4

**Comment by GotoLink** [comment] 2015-09-12 17:09
Duplicate of #94.

**Closed by GotoLink** 2015-09-12 17:09 UTC
