### ISSUE TITLE
Ticking Screen:Client Side Crash

### ISSUE THREAD

**Issue by LegendaryAdmin** [Mine-and-blade-admin/Battlegear2#149] opened 2015-01-11 20:33 UTC
I found a bug when clicking on the ground with dual wield enabled, it crashes the client. Here is the error log:

http://pastebin.com/Eb3fc6i8

installed mods:
Battlegear
AppleCore
BiomesOplenty
ClimateControl
CoroUtil
CustomNpcs
DoomlikeDungeons
DragonMounts
Enviromine
GraveStone
HungerOverhaul
IguanaTweaks
KwastiBustMonsters
MultMine
OceanCraft
HarvestCraft
PlayerAPI
RoguelikeDungeons
SKC-Core
SlabCraft
SmartCore
SmartMoving
SpecialMobs
SpiceofLife
Staircraft
UpdateChecker
BalkonWeaponMod
Weather2
WildCaves
ZombieAwareness

**Comment by GotoLink** [comment] 2015-01-12 01:44
Hum. The crash report points an issue with OpenGL occlusion...a video driver issue ?
Are your sure this is the crash log that happened when you right clicked. The time on this one is 1/11/15 3:37 AM.
I couldn't reproduce the issue empty-handed or equipped with swords/shields. Could you describe the player inventory ?

**Comment by LegendaryAdmin** [comment] 2015-01-12 01:52
This has happened with any player that has an empty hand when dual wielding. I did not specify that the hand has to be empty >.<

**Comment by LegendaryAdmin** [comment] 2015-01-12 09:56
So after realizing I had not actually answered your question,  I went back and did a few proper tests.

I ran 3 tests; Empty inventory, Inventory full of dirt, and an inventory full of tools.

When I went to look for the log, there was not one. The issue I pasted you I believe was just a coincidence that it occurred near the same time and I did not check the actual time on the log. My apologies there.

This is what I have figured out:

It is still most certainly happening however it only happens when I click an unusable block with my right click only and it does not occur when I right click a usable block like a chest or crafting table.

This is the only entry I can find of the event:
[09:42:45] [Server thread/INFO]: _LargeFarva_ lost connection: Internal server error

Once again, my apologies for the faulty information, and thank you for taking a look =]

**Comment by LegendaryAdmin** [comment] 2015-01-18 21:12
After further testing, this seems to only be a problem with Cauldron. When I run the modpack on single player forge, this does not happen. We are using v. cauldron-1.7.10-1.1236.05.211. 

I suspect it is Cauldron itself that is the issue, however-perhaps Extra Hard Mode is throwing a wrench in the gears (custom physics)...

I will run some other tests and remove plugins etc to see if that changes anything and report back later tonight or tomorrow.

Our list of plugins:

ChunkSpawnerLimiter
CoreProtect_2.10.0
CustomDeathMessages
Essentials
ExtraHardMode-3.5.2
HolographicDisplays
Lockette
NetherRoofProtect
PlayerActivity
ProtocolLib-3.4.0
PvPManager
RandomLocation_v4.73
Sleep
Vault-1.4.1
WorldBorder
WorldEdit
WorldGuard

**Comment by LegendaryAdmin** [comment] 2015-01-20 12:06
Found an update to cauldron v. 1.7.10-1.1236.05.212

Problem persists.

**Comment by LegendaryAdmin** [comment] 2015-01-21 01:29
Found this a while back but I know I have the right version so I had forgotten about it, I thought it would be worth mentioning though: 

[21:51:37] [main/WARN] [FML/]: Missing @MCVersion: mods.battlegear2.coremod.BattlegearLoadingPlugin

**Comment by GotoLink** [comment] 2015-09-03 18:08
Should have been fixed by 1.0.8.1. Closing.

**Closed by GotoLink** 2015-09-03 18:08 UTC
Labels: cauldron/mcpc related
