### ISSUE TITLE
open blocks conflict.

### ISSUE THREAD

**Issue by HardInk** [Mine-and-blade-admin/Battlegear2#186] opened 2015-06-02 19:52 UTC
Openblocks grave does not store dual weild items, and armor is deleted upon death as well. swapping to two hands from main hotbar also removes armor buggily

**Comment by GotoLink** [comment] 2015-06-02 20:36
Duplicate of #142 ?

**Comment by HardInk** [comment] 2015-06-03 03:02
no, the open blocks grave is not a death chest system, more along the lines of a state save system, storing the items in a separate .dat file until the grave is broken.

**Comment by GotoLink** [comment] 2015-06-03 16:15
We totally don't touch the armor at any point. All items in battle slots are dropped exactly the same as the other slots.
I'll still blame Openblocks implementation, even if it isn't a conventional chest.

**Comment by GotoLink** [comment] 2015-09-03 21:16
Unable to reproduce with Battlegear 1.0.8.1, OpenLibs 0.8, OpenBlocks 1.4.4.
Closing.

**Closed by GotoLink** 2015-09-03 21:16 UTC
Labels: missing info
